# Generated by Django 3.2.5 on 2021-08-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('disease_Problem', models.TextField(max_length=500)),
                ('doctor_name', models.CharField(max_length=40)),
                ('doctor_fees', models.IntegerField(default=500)),
                ('started_meds_on_date', models.DateField()),
            ],
        ),
    ]
